[build]
command = "pnpm run export"
publish = "out"
environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[template.environment]
NEXT_PUBLIC_SLUG = "zwr-event-agency.commercelayer.io"